### ISSUE TITLE
Can't import porject

### ISSUE THREAD

**Issue by tryjaka** [lucassene/2DStealth#1]
It seems that the files are incomplete such as asset. Can you update the files?
and when ran nontheless it returns:
[2D stealth - error.txt](https://github.com/lucassene/2DStealth/files/6404428/2D.stealth.-.error.txt)

**Comment by lucassene** [comment]
Hey @tryjaka, thanks for your feedback!

I just uploaded the assets folder to the project and now you should be able to import the project properly.

Lucas Sene

**Comment by tryjaka** [comment]
Alright will post if i run into some issue. Thankyou very much
